<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsThousandLiPackageArtifact>true</IsThousandLiPackageArtifact>
    <ThousandLiFrontendDirectory>$(MSBuildProjectDirectory)/frontend</ThousandLiFrontendDirectory>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ThousandLi.Contracts/ThousandLi.Contracts.csproj" />
    <ProjectReference Include="../../src/ThousandLi.GameAuthoring/ThousandLi.GameAuthoring.csproj" />
    <ProjectReference Include="../../src/ThousandLi.GameHelper/ThousandLi.GameHelper.csproj" />
  </ItemGroup>
</Project>
