<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" />
    <ProjectReference Include="../../src/ThousandLi.ExpertAuthoring/ThousandLi.ExpertAuthoring.csproj" />
  </ItemGroup>
</Project>
