<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsThousandLiPackageArtifact>true</IsThousandLiPackageArtifact>
    <IsThousandLiExpertPackageArtifact>true</IsThousandLiExpertPackageArtifact>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ThousandLi.ExpertAuthoring/ThousandLi.ExpertAuthoring.csproj" />
  </ItemGroup>
</Project>
