<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ThousandLi.Contracts/ThousandLi.Contracts.csproj" />
    <ProjectReference Include="../../src/ThousandLi.GameAuthoring/ThousandLi.GameAuthoring.csproj" />
    <ProjectReference Include="../../src/ThousandLi.GameHelper/ThousandLi.GameHelper.csproj" />
    <ProjectReference Include="../../src/ThousandLi.Testing/ThousandLi.Testing.csproj" />
    <ProjectReference Include="../../src/ThousandLi.DevHost/ThousandLi.DevHost.csproj" />
    <ProjectReference Include="../../samples/ThousandLi.SampleGame/ThousandLi.SampleGame.csproj" />
  </ItemGroup>
</Project>
