<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" />
  </ItemGroup>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ThousandLi.Contracts/ThousandLi.Contracts.csproj" />
  </ItemGroup>
</Project>
